version: "3.9"

services:
  web:
    build: web
    container_name: django-web
    volumes:
      - static:/var/www/static:ro
    environment:
      - APP_HOST=${APP_HOST:-app}
      - APP_PORT=${APP_PORT:-8000}
      - WEB_PORT=${WEB_PORT:-80}
    ports:
      - ${WEB_PORT:-80}:${WEB_PORT:-80}
    depends_on:
      - app

  app:
    build: .
    container_name: django-app
    volumes:
      - .:/home/django/workspace
      - static:/home/django/workspace/static
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SECRET_KEY=${SECRET_KEY:-secretKey}
      - APP_WORKERS=${APP_WORKERS:-2}
      - APP_HOSTS=${APP_HOSTS:-*}
      - APP_ADDR=${APP_ADDR:-0.0.0.0}
      - APP_PORT=${APP_PORT:-8000}
      - ADMIN_NAME=${ADMIN_NAME:-admin}
      - ADMIN_MAIL=${ADMIN_MAIL:-admin@example.com}
      - ADMIN_PASS=${ADMIN_PASS:-password}
      - DATABASE_NAME=${DATABASE_NAME:-database}
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASS=${DATABASE_PASS:-postgres}
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
    ports:
      - ${APP_PORT:-8000}:${APP_PORT:-8000}
    depends_on:
      - db

  db:
    container_name: django-db
    image: postgres:13-alpine
    user: postgres
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-database}
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASS:-postgres}
      - PGPORT=${DATABASE_PORT:-5432}
    ports:
      - ${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}

volumes:
  database:
    name: django-database
  static:
    name: django-static

networks:
  default:
    name: django_network
